<?php

return [
    'show_warnings'         => false,
    'public_path'           => null,
    'convert_entities'      => true,
    'options' => [
        'font_dir'            => storage_path('fonts/'),
        'font_cache'          => storage_path('fonts/'),
        'temp_dir'            => sys_get_temp_dir(),
        'chroot'              => realpath(base_path()),
        'allowed_remote_hosts'=> null,
        'log_output_file'     => null,
        'default_media_type'  => 'screen',
        'default_paper_size'  => 'a4',
        'default_paper_orientation' => 'portrait',
        'default_font'        => 'serif',
        'dpi'                 => 96,
        'font_height_ratio'   => 1.1,
        'enable_php'          => false,
        'enable_javascript'   => true,
        'enable_remote'       => true,
        'allowed_protocols'   => [
            'file://' => ['rules' => []],
            'http://'  => ['rules' => []],
            'https://' => ['rules' => []],
        ],
        'debug_png'           => false,
        'debug_keep_temp'     => false,
        'debug_css'           => false,
        'debug_layout'        => false,
        'debug_layout_lines'  => true,
        'debug_layout_blocks' => true,
        'debug_layout_inline' => true,
        'debug_layout_padding'=> false,
        'debug_layout_lines_width' => 0.5,
        'pdf_backend'         => 'CPDF',
        'pdffontpath'         => null,
        'unicode_enabled'     => true,
        'page_size'           => 'letter',
        'enable_html5_parser' => true,
    ],
];
